In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
#connection
conn = sql.connect('database.sqlite')
conn

In [3]:
a = conn.execute('select * from Salaries')
a

In [4]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [5]:
pd.read_sql_query('select * from Salaries',conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [6]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [9]:
q = '''select * from Salaries'''
sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

1. Top 10 highest paid employees (by TotalPayBenefits)

In [10]:
q= '''SELECT EmployeeName, JobTitle, TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC
LIMIT 10'''

sql_query(q)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
2,David Shinn,Deputy Chief 3,510732.68
3,Amy P Hart,Asst Med Examiner,479652.21
4,William J Coaker Jr.,Chief Investment Officer,436224.36
5,Gregory P Suhr,Chief of Police,425815.28
6,Joanne M Hayes-White,"Chief, Fire Department",422353.40
7,Gregory P Suhr,Chief of Police,418019.22
8,Joanne M Hayes-White,"Chief, Fire Department",417435.10
9,Ellen G Moffatt,Asst Med Examiner,415767.94

2. Find which year has missing data of Employees with 'Not Provided'/ 'Not provided' .

In [14]:
q = '''select * from Salaries
    where year == "Not provided" 
    '''

sql_query(q)

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

3. Number of unique agencies

In [15]:
q= '''SELECT COUNT(DISTINCT Agency) AS UniqueAgencyCount
FROM Salaries'''

sql_query(q)

   UniqueAgencyCount
0                  1

4. Show Average BasePay, OvertimePay, and TotalPay for year 2011

In [17]:
q= '''select 
    avg(basepay) as average_basepay,
    avg(overtimepay) as average_overtimepay,
    avg(totalpay) as average_totalpay,
    year
from salaries
where year = 2011
'''

sql_query(q)

   average_basepay  average_overtimepay  average_totalpay  Year
0     63595.956517          4531.065429      71744.103871  2011

5. Plot the top 10 job titles with the highest TotalPay in 2014.

In [22]:
q= '''select jobtitle, avg(totalpay) as AverageTotalPay, year
    from salaries
    where year = 2014
    group by jobtitle
    order by AverageTotalPay desc
    limit 10;
'''
sql_query(q)

                       JobTitle  AverageTotalPay  Year
0      Chief Investment Officer    339653.700000  2014
1               Chief of Police    326716.760000  2014
2        Chief, Fire Department    326233.440000  2014
3    Gen Mgr, Public Trnsp Dept    294000.180000  2014
4   Dep Chf of Dept (Fire Dept)    285575.785000  2014
5                Deputy Chief 3    282918.775000  2014
6            Administrator, DPH    282619.960000  2014
7                         Mayor    281537.170000  2014
8  Asst Chf of Dept (Fire Dept)    279768.958333  2014
9                   Dept Head V    279408.864000  2014

6. Which job titles have overtime pay exceeding $150,000 exluding 'Not provided'

In [23]:
q= '''select jobtitle, employeename, overtimepay
    from salaries
    where overtimepay > 150000
    and jobtitle != 'not provided'
'''
sql_query(q)

                           JobTitle        EmployeeName   OvertimePay
0   CAPTAIN III (POLICE DEPARTMENT)        GARY JIMENEZ     245131.88
1      Lieutenant, Fire Suppression      Gary Altenberg     220909.48
2         EMT/Paramedic/Firefighter   Frederick Binkley     192424.49
3                       Firefighter      Scott Scholzen     160418.47
4      Lieutenant, Fire Suppression    Gary L Altenberg     163477.81
5                    Deputy Sheriff       Whitney P Yee     196689.18
6                    Deputy Sheriff       Barry J Bloom     156077.49
7                    Deputy Sheriff  Antonio B Santiago     173547.73
8                    Deputy Sheriff       Barry J Bloom     173178.23
9                    Deputy Sheriff       Whitney P Yee     169659.92
10                     Not provided        Not provided  Not Provided
11                     Not provided        Not provided  Not Provided
12                     Not provided        Not provided  Not Provided
13                     Not provided        Not provided  Not Provided

7. Find all employees whose job titles contain the word “CHIEF”

In [28]:
q= '''select employeename, jobtitle
    from salaries
    where jobtitle like '%chief%' collate nocase;
'''

sql_query(q)

            EmployeeName                                      JobTitle
0        PATRICK GARDNER  DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
1         DAVID SULLIVAN                     ASSISTANT DEPUTY CHIEF II
2              ALSON LEE            BATTALION CHIEF, (FIRE DEPARTMENT)
3         MICHAEL MORRIS            BATTALION CHIEF, (FIRE DEPARTMENT)
4     JOANNE HAYES-WHITE        CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
..                   ...                                           ...
622     Sharon C Jackson                Chief Deputy Adlt Probation Of
623          Anita S Lee                                   Chief Clerk
624     George D Vaughan                      Chief Nursery Specialist
625  Patrick W Gillespie                              Chief Preparator
626  Christopher L Ochoa                     Chief Stationary Engineer

[627 rows x 2 columns]

8. Count how many employees have job titles containing “ENGINEER” and “Fire” in year 2012 and 2013

In [29]:
q= '''select count(*) as employee_count
    from salaries
    where (jobtitle like '%engineer%' and jobtitle like '%fire%')
    and year in (2012, 2013)
    collate nocase'''

sql_query(q)

   employee_count
0              16

9. Distinct job titles starting with "CAPTAIN"

In [30]:
q= '''select distinct jobtitle
    from salaries
    where jobtitle like 'captain%' collate nocase
'''
sql_query(q)

                                            JobTitle
0                    CAPTAIN III (POLICE DEPARTMENT)
1              CAPTAIN, EMERGENCYCY MEDICAL SERVICES
2                          CAPTAIN, FIRE SUPPRESSION
3  CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC ...
4                                          Captain 3
5                          Captain, Fire Suppression
6                        Captain, Emergency Med Svcs
7                         Captain, (Fire Department)

10. Employees having basepay > 50k and totalpay < 150000 exlucding 'Not Provided'

In [31]:
q= '''select employeename, jobtitle, basepay, totalpay
    from salaries
    where basepay != 'not provided'
    and cast(basepay as real) > 50000
    and totalpay < 150000
    '''

sql_query(q)

,EmployeeName,JobTitle,BasePay,TotalPay
0,JAY DOWKE,POLICE OFFICER III,112380.37,149987.24
1,MURRAY BOND,MANAGER VI - MUNICIPAL TRANSPORTATION AGENCY,149975.80,149975.80
2,MARILOU GAN,REGISTERED NURSE,119703.78,149970.85
3,BRIAN COLLINS,FIREFIGHTER,105934.65,149964.61
4,GREGORY NEAL,POLICE OFFICER I,106065.20,149952.47
...,...,...,...,...
86650,Renee J Allen,Special Nurse,52428.53,53458.31
86651,Melody M Butterworth,Attorney (Civil/Criminal),52389.79,52555.44
86652,Stephanie Reidy,Special Nurse,51668.70,51785.23
86653,Paul E Maltzer,Planner 5,51673.98,51673.98
86654,Kathleen N Yumang,Special Nurse,50342.45,50348.91